--use flights;

/*ALTER TABLE FLIGHT
ADD NUM_PASS INT;

ALTER TABLE AGENCY
ADD NUM_BOOK INT;

CREATE TRIGGER tr_insert_res ON BOOKING
AFTER INSERT
AS
UPDATE FLIGHT
SET NUM_PASS=NUM_PASS+1
UPDATE AGENCY
SET NUM_BOOK=NUM_BOOK+1;

CREATE TRIGGER tr_del_res on BOOKING
AFTER DELETE
AS 
UPDATE FLIGHT
SET NUM_PASS=NUM_PASS-1
UPDATE AGENCY 
SET NUM_BOOK=NUM_BOOK-1;



CREATE TRIGGER tr_update_res on BOOKING
AFTER UPDATE
AS
UPDATE FLIGHT
SET NUM_PASS=NUM_PASS-1
WHERE FNUMBER IN  (SELECT fNumber FROM DELETED);
UPDATE FLIGHT
SET NUM_PASS=NUM_PASS+1
WHERE FNUMBER IN (SELECT fNumber FROM INSERTED);
UPDATE AGENCY
SET NUM_BOOK=NUM_BOOK-1
WHERE NAME IN (SELECT AGENCY FROM DELETED);
UPDATE AGENCY
SET NUM_BOOK=NUM_BOOK+1
WHERE NAME IN (SELECT AGENCY FROM INSERTED);

*/